version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: sapa_tazkia_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  mysql:
    image: mysql:8.0
    container_name: sapa_tazkia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ican1234
      MYSQL_DATABASE: sapa_tazkia
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  # --- Konfigurasi Redis Baru ---
  redis:
    image: redis:latest
    container_name: sapa_tazkia_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always